server:
  port: 8443

spring:
  cors:
    allowed-origins: http://localhost:5173

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: Dl8BC4eahQoUQ5Q7ju2j
            client-secret: WS7F_B7hRK
            redirect-uri: http://localhost:8443/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-name: google
            client-id: 629233939928-ljgk3bm01ikcpherjsoo2jq928rdjukd.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8443/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: jdbc:mysql://localhost:3306/dogcatdang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
