server:
  port: 9090

# database 연동 설정
spring:
  cors:
    allowed-origins: https://i10e202.p.ssafy.io
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: jPt9fIucOQnjV_ZG0Pf2
            client-secret: ph3HbCjgk2
            redirect-uri: https://i10e202.p.ssafy.io/api/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-name: google
            client-id: 482443242773-o3qodrbamn53ff593o4rgpot79qhulqg.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://i10e202.p.ssafy.io/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: jdbc:mysql://i10e202.p.ssafy.io:3306/dogcatdang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

log:
  levels:
